import type { PopulatedClassTimetable } from "@/lib/schema/class/class-timetable-schema";

export const examplePopulatedTimetable: PopulatedClassTimetable = {
  _id: "timetable_001",
  class_id: "class_10A",
  academic_year: "2024-2025",
  weekly_schedule: [
    // MONDAY
    {
      day: "Monday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "mon_1",
          type: "subject",
          title: "Mathematics - Algebra",
          description: "Linear equations and graphs",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "mon_2",
          type: "subject",
          title: "Physics - Mechanics",
          description: "Laws of motion",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "mon_3",
          type: "subject",
          title: "Chemistry - Organic",
          description: "Hydrocarbon compounds",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "chem_001",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Williams",
            user_id: "user_teacher_003",
            image: "/teachers/williams.jpg",
          },
          subject: {
            id: "chem_001",
            _id: "chem_001",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "mon_break1",
          type: "break",
          title: "Morning Break",
          description: "Short refreshment break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "mon_4",
          type: "subject",
          title: "English Literature",
          description: "Shakespearean sonnets",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "mon_5",
          type: "subject",
          title: "World History",
          description: "Industrial Revolution",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#F1948A",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "history_001",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mr. Brown",
            user_id: "user_teacher_005",
            image: "/teachers/brown.jpg",
          },
          subject: {
            id: "history_001",
            _id: "history_001",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "mon_6",
          type: "free",
          title: "Free Period",
          description: "Self-study time",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "mon_lunch",
          type: "lunch",
          title: "Lunch Break",
          description: "Lunch in cafeteria",
          order: 8,
          start_offset: 260,
          duration_minutes: 60,
          color_code: "#F8C471",
          enabled: true,
        },
        {
          period_id: "mon_7",
          type: "subject",
          title: "Biology - Cell Structure",
          description: "Mitochondria and organelles",
          order: 9,
          start_offset: 320,
          duration_minutes: 40,
          color_code: "#82E0AA",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "bio_001",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Dr. Garcia",
            user_id: "user_teacher_006",
            image: "/teachers/garcia.jpg",
          },
          subject: {
            id: "bio_001",
            _id: "bio_001",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "mon_8",
          type: "subject",
          title: "Geography",
          description: "Climate zones and biomes",
          order: 10,
          start_offset: 360,
          duration_minutes: 40,
          color_code: "#85C1E9",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "geo_001",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Mrs. Wilson",
            user_id: "user_teacher_007",
            image: "/teachers/wilson.jpg",
          },
          subject: {
            id: "geo_001",
            _id: "geo_001",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "mon_break2",
          type: "break",
          title: "Afternoon Break",
          description: "Short break before final periods",
          order: 11,
          start_offset: 400,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "mon_9",
          type: "subject",
          title: "Computer Science",
          description: "Python programming basics",
          order: 12,
          start_offset: 420,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "cs_001",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Taylor",
            user_id: "user_teacher_008",
            image: "/teachers/taylor.jpg",
          },
          subject: {
            id: "cs_001",
            _id: "cs_001",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "mon_10",
          type: "subject",
          title: "Physical Education",
          description: "Basketball practice",
          order: 13,
          start_offset: 460,
          duration_minutes: 40,
          color_code: "#F9E79F",
          enabled: true,
          teacher_id: "teacher_009",
          subject_id: "pe_001",
          teacher: {
            id: "teacher_009",
            _id: "teacher_009",
            name: "Coach Martinez",
            user_id: "user_teacher_009",
            image: "/teachers/martinez.jpg",
          },
          subject: {
            id: "pe_001",
            _id: "pe_001",
            name: "Physical Education",
            code: "PE101",
          },
        },
      ],
    },
    // TUESDAY
    {
      day: "Tuesday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "tue_1",
          type: "subject",
          title: "English Literature",
          description: "Poetry analysis",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "tue_2",
          type: "subject",
          title: "Mathematics - Calculus",
          description: "Derivatives and limits",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "tue_3",
          type: "subject",
          title: "Physics - Waves",
          description: "Sound and light waves",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "tue_break1",
          type: "break",
          title: "Morning Break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "tue_4",
          type: "subject",
          title: "Chemistry - Inorganic",
          description: "Periodic table trends",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "chem_001",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Williams",
            user_id: "user_teacher_003",
            image: "/teachers/williams.jpg",
          },
          subject: {
            id: "chem_001",
            _id: "chem_001",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "tue_5",
          type: "subject",
          title: "Geography",
          description: "Plate tectonics",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#85C1E9",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "geo_001",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Mrs. Wilson",
            user_id: "user_teacher_007",
            image: "/teachers/wilson.jpg",
          },
          subject: {
            id: "geo_001",
            _id: "geo_001",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "tue_6",
          type: "free",
          title: "Free Period",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "tue_lunch",
          type: "lunch",
          title: "Lunch Break",
          order: 8,
          start_offset: 260,
          duration_minutes: 60,
          color_code: "#F8C471",
          enabled: true,
        },
        {
          period_id: "tue_7",
          type: "subject",
          title: "Biology - Genetics",
          description: "Mendelian inheritance",
          order: 9,
          start_offset: 320,
          duration_minutes: 40,
          color_code: "#82E0AA",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "bio_001",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Dr. Garcia",
            user_id: "user_teacher_006",
            image: "/teachers/garcia.jpg",
          },
          subject: {
            id: "bio_001",
            _id: "bio_001",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "tue_8",
          type: "subject",
          title: "History",
          description: "World War I",
          order: 10,
          start_offset: 360,
          duration_minutes: 40,
          color_code: "#F1948A",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "history_001",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mr. Brown",
            user_id: "user_teacher_005",
            image: "/teachers/brown.jpg",
          },
          subject: {
            id: "history_001",
            _id: "history_001",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "tue_break2",
          type: "break",
          title: "Afternoon Break",
          order: 11,
          start_offset: 400,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "tue_9",
          type: "subject",
          title: "Computer Science",
          description: "Data structures",
          order: 12,
          start_offset: 420,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "cs_001",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Taylor",
            user_id: "user_teacher_008",
            image: "/teachers/taylor.jpg",
          },
          subject: {
            id: "cs_001",
            _id: "cs_001",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "tue_10",
          type: "subject",
          title: "Art Class",
          description: "Watercolor techniques",
          order: 13,
          start_offset: 460,
          duration_minutes: 40,
          color_code: "#F8C471",
          enabled: true,
          teacher_id: "teacher_010",
          subject_id: "art_001",
          teacher: {
            id: "teacher_010",
            _id: "teacher_010",
            name: "Ms. Rodriguez",
            user_id: "user_teacher_010",
            image: "/teachers/rodriguez.jpg",
          },
          subject: {
            id: "art_001",
            _id: "art_001",
            name: "Art",
            code: "ART101",
          },
        },
      ],
    },
    // WEDNESDAY
    {
      day: "Wednesday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "wed_1",
          type: "subject",
          title: "Physics - Optics",
          description: "Light reflection and refraction",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "wed_2",
          type: "subject",
          title: "Chemistry - Analytical",
          description: "Titration methods",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "chem_001",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Williams",
            user_id: "user_teacher_003",
            image: "/teachers/williams.jpg",
          },
          subject: {
            id: "chem_001",
            _id: "chem_001",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "wed_3",
          type: "subject",
          title: "Mathematics - Geometry",
          description: "Trigonometry basics",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "wed_break1",
          type: "break",
          title: "Morning Break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "wed_4",
          type: "subject",
          title: "Biology - Ecology",
          description: "Ecosystem relationships",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#82E0AA",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "bio_001",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Dr. Garcia",
            user_id: "user_teacher_006",
            image: "/teachers/garcia.jpg",
          },
          subject: {
            id: "bio_001",
            _id: "bio_001",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "wed_5",
          type: "subject",
          title: "English Grammar",
          description: "Sentence structure",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "wed_6",
          type: "free",
          title: "Free Period",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "wed_lunch",
          type: "lunch",
          title: "Lunch Break",
          order: 8,
          start_offset: 260,
          duration_minutes: 60,
          color_code: "#F8C471",
          enabled: true,
        },
        {
          period_id: "wed_7",
          type: "subject",
          title: "History - Ancient",
          description: "Egyptian civilization",
          order: 9,
          start_offset: 320,
          duration_minutes: 40,
          color_code: "#F1948A",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "history_001",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mr. Brown",
            user_id: "user_teacher_005",
            image: "/teachers/brown.jpg",
          },
          subject: {
            id: "history_001",
            _id: "history_001",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "wed_8",
          type: "subject",
          title: "Geography - Political",
          description: "World capitals",
          order: 10,
          start_offset: 360,
          duration_minutes: 40,
          color_code: "#85C1E9",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "geo_001",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Mrs. Wilson",
            user_id: "user_teacher_007",
            image: "/teachers/wilson.jpg",
          },
          subject: {
            id: "geo_001",
            _id: "geo_001",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "wed_break2",
          type: "break",
          title: "Afternoon Break",
          order: 11,
          start_offset: 400,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "wed_9",
          type: "subject",
          title: "Computer Science Lab",
          description: "Hands-on programming",
          order: 12,
          start_offset: 420,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "cs_001",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Taylor",
            user_id: "user_teacher_008",
            image: "/teachers/taylor.jpg",
          },
          subject: {
            id: "cs_001",
            _id: "cs_001",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "wed_10",
          type: "subject",
          title: "Physical Education",
          description: "Swimming lessons",
          order: 13,
          start_offset: 460,
          duration_minutes: 40,
          color_code: "#F9E79F",
          enabled: true,
          teacher_id: "teacher_009",
          subject_id: "pe_001",
          teacher: {
            id: "teacher_009",
            _id: "teacher_009",
            name: "Coach Martinez",
            user_id: "user_teacher_009",
            image: "/teachers/martinez.jpg",
          },
          subject: {
            id: "pe_001",
            _id: "pe_001",
            name: "Physical Education",
            code: "PE101",
          },
        },
      ],
    },
    // THURSDAY
    {
      day: "Thursday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "thu_1",
          type: "subject",
          title: "Biology - Human Anatomy",
          description: "Skeletal system",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#82E0AA",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "bio_001",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Dr. Garcia",
            user_id: "user_teacher_006",
            image: "/teachers/garcia.jpg",
          },
          subject: {
            id: "bio_001",
            _id: "bio_001",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "thu_2",
          type: "subject",
          title: "Mathematics - Statistics",
          description: "Data analysis",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "thu_3",
          type: "subject",
          title: "English Writing",
          description: "Essay composition",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "thu_break1",
          type: "break",
          title: "Morning Break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "thu_4",
          type: "subject",
          title: "Physics Lab",
          description: "Practical experiments",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "thu_5",
          type: "subject",
          title: "Chemistry Lab",
          description: "Chemical reactions",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "chem_001",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Williams",
            user_id: "user_teacher_003",
            image: "/teachers/williams.jpg",
          },
          subject: {
            id: "chem_001",
            _id: "chem_001",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "thu_6",
          type: "free",
          title: "Free Period",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "thu_lunch",
          type: "lunch",
          title: "Lunch Break",
          order: 8,
          start_offset: 260,
          duration_minutes: 60,
          color_code: "#F8C471",
          enabled: true,
        },
        {
          period_id: "thu_7",
          type: "subject",
          title: "History - Modern",
          description: "20th century events",
          order: 9,
          start_offset: 320,
          duration_minutes: 40,
          color_code: "#F1948A",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "history_001",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mr. Brown",
            user_id: "user_teacher_005",
            image: "/teachers/brown.jpg",
          },
          subject: {
            id: "history_001",
            _id: "history_001",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "thu_8",
          type: "subject",
          title: "Geography - Physical",
          description: "Landforms and erosion",
          order: 10,
          start_offset: 360,
          duration_minutes: 40,
          color_code: "#85C1E9",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "geo_001",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Mrs. Wilson",
            user_id: "user_teacher_007",
            image: "/teachers/wilson.jpg",
          },
          subject: {
            id: "geo_001",
            _id: "geo_001",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "thu_break2",
          type: "break",
          title: "Afternoon Break",
          order: 11,
          start_offset: 400,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "thu_9",
          type: "subject",
          title: "Computer Science",
          description: "Algorithms and logic",
          order: 12,
          start_offset: 420,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "cs_001",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Taylor",
            user_id: "user_teacher_008",
            image: "/teachers/taylor.jpg",
          },
          subject: {
            id: "cs_001",
            _id: "cs_001",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "thu_10",
          type: "subject",
          title: "Music",
          description: "Music theory basics",
          order: 13,
          start_offset: 460,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_011",
          subject_id: "music_001",
          teacher: {
            id: "teacher_011",
            _id: "teacher_011",
            name: "Mr. Lee",
            user_id: "user_teacher_011",
            image: "/teachers/lee.jpg",
          },
          subject: {
            id: "music_001",
            _id: "music_001",
            name: "Music",
            code: "MUS101",
          },
        },
      ],
    },
    // FRIDAY
    {
      day: "Friday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "fri_1",
          type: "subject",
          title: "History - Medieval",
          description: "Feudal system",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#F1948A",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "history_001",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mr. Brown",
            user_id: "user_teacher_005",
            image: "/teachers/brown.jpg",
          },
          subject: {
            id: "history_001",
            _id: "history_001",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "fri_2",
          type: "subject",
          title: "Geography - Economic",
          description: "Resource distribution",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#85C1E9",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "geo_001",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Mrs. Wilson",
            user_id: "user_teacher_007",
            image: "/teachers/wilson.jpg",
          },
          subject: {
            id: "geo_001",
            _id: "geo_001",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "fri_3",
          type: "subject",
          title: "English Drama",
          description: "Play reading",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "fri_break1",
          type: "break",
          title: "Morning Break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "fri_4",
          type: "subject",
          title: "Mathematics - Probability",
          description: "Chance and statistics",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "fri_5",
          type: "subject",
          title: "Biology Lab",
          description: "Microscope work",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#82E0AA",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "bio_001",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Dr. Garcia",
            user_id: "user_teacher_006",
            image: "/teachers/garcia.jpg",
          },
          subject: {
            id: "bio_001",
            _id: "bio_001",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "fri_6",
          type: "free",
          title: "Free Period",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "fri_lunch",
          type: "lunch",
          title: "Lunch Break",
          order: 8,
          start_offset: 260,
          duration_minutes: 60,
          color_code: "#F8C471",
          enabled: true,
        },
        {
          period_id: "fri_7",
          type: "subject",
          title: "Physics - Thermodynamics",
          description: "Heat transfer",
          order: 9,
          start_offset: 320,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "fri_8",
          type: "subject",
          title: "Chemistry - Biochemistry",
          description: "Organic compounds",
          order: 10,
          start_offset: 360,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "chem_001",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Williams",
            user_id: "user_teacher_003",
            image: "/teachers/williams.jpg",
          },
          subject: {
            id: "chem_001",
            _id: "chem_001",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "fri_break2",
          type: "break",
          title: "Afternoon Break",
          order: 11,
          start_offset: 400,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "fri_9",
          type: "subject",
          title: "Computer Science",
          description: "Web development basics",
          order: 12,
          start_offset: 420,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "cs_001",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Taylor",
            user_id: "user_teacher_008",
            image: "/teachers/taylor.jpg",
          },
          subject: {
            id: "cs_001",
            _id: "cs_001",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "fri_10",
          type: "subject",
          title: "Physical Education",
          description: "Team sports",
          order: 13,
          start_offset: 460,
          duration_minutes: 40,
          color_code: "#F9E79F",
          enabled: true,
          teacher_id: "teacher_009",
          subject_id: "pe_001",
          teacher: {
            id: "teacher_009",
            _id: "teacher_009",
            name: "Coach Martinez",
            user_id: "user_teacher_009",
            image: "/teachers/martinez.jpg",
          },
          subject: {
            id: "pe_001",
            _id: "pe_001",
            name: "Physical Education",
            code: "PE101",
          },
        },
      ],
    },
    // SATURDAY
    {
      day: "Saturday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "sat_1",
          type: "subject",
          title: "Mathematics Workshop",
          description: "Problem solving session",
          order: 1,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "math_001",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            user_id: "user_teacher_001",
            image: "/teachers/smith.jpg",
          },
          subject: {
            id: "math_001",
            _id: "math_001",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "sat_2",
          type: "subject",
          title: "Science Lab",
          description: "Physics experiments",
          order: 2,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "physics_001",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            user_id: "user_teacher_002",
            image: "/teachers/johnson.jpg",
          },
          subject: {
            id: "physics_001",
            _id: "physics_001",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "sat_3",
          type: "subject",
          title: "Language Club",
          description: "Debate and discussion",
          order: 3,
          start_offset: 80,
          duration_minutes: 40,
          color_code: "#BB8FCE",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "english_001",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            user_id: "user_teacher_004",
            image: "/teachers/davis.jpg",
          },
          subject: {
            id: "english_001",
            _id: "english_001",
            name: "English Literature",
            code: "ENG201",
          },
        },
        {
          period_id: "sat_break",
          type: "break",
          title: "Short Break",
          order: 4,
          start_offset: 120,
          duration_minutes: 20,
          color_code: "#F7DC6F",
          enabled: true,
        },
        {
          period_id: "sat_4",
          type: "subject",
          title: "Art Class",
          description: "Drawing techniques",
          order: 5,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#F8C471",
          enabled: true,
          teacher_id: "teacher_010",
          subject_id: "art_001",
          teacher: {
            id: "teacher_010",
            _id: "teacher_010",
            name: "Ms. Rodriguez",
            user_id: "user_teacher_010",
            image: "/teachers/rodriguez.jpg",
          },
          subject: {
            id: "art_001",
            _id: "art_001",
            name: "Art",
            code: "ART101",
          },
        },
        {
          period_id: "sat_5",
          type: "free",
          title: "Free Activity",
          description: "Choose your activity",
          order: 6,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#A6ACAF",
          enabled: true,
        },
        {
          period_id: "sat_6",
          type: "subject",
          title: "Music",
          description: "Vocal training",
          order: 7,
          start_offset: 220,
          duration_minutes: 40,
          color_code: "#D7BDE2",
          enabled: true,
          teacher_id: "teacher_011",
          subject_id: "music_001",
          teacher: {
            id: "teacher_011",
            _id: "teacher_011",
            name: "Mr. Lee",
            user_id: "user_teacher_011",
            image: "/teachers/lee.jpg",
          },
          subject: {
            id: "music_001",
            _id: "music_001",
            name: "Music",
            code: "MUS101",
          },
        },
      ],
    },
    // SUNDAY
    {
      day: "Sunday",
      is_holiday: true,
      // No start_on required for holidays
      periods: [],
    },
  ],
  class: {
    id: "class_10A",
    _id: "class_10A",
    name: "Grade 10-A",
    username: "class-10a",
    image: "/classes/10a.jpg",
  },
  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2024-01-20T14:30:00Z",
};
