import type { PopulatedClassTimetable } from "@/lib/schema/class/class-timetable-schema";

export const populatedTimetableExample: PopulatedClassTimetable = {
  _id: "timetable_001",
  class_id: "class_10A",
  academic_year: "2024-2025",

  weekly_schedule: [
    // ==================== MONDAY ====================
    {
      day: "Monday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "mon_1",
          type: "subject",
          title: "Mathematics",
          description: "Advanced Algebra and Calculus",
          order: 0,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "sub_math",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            image: "/images/teachers/smith.jpg",
            user_id: "user_teacher_001",
          },
          subject: {
            id: "sub_math",
            _id: "sub_math",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "mon_2",
          type: "subject",
          title: "Physics",
          description: "Mechanics and Thermodynamics",
          order: 1,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "sub_physics",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            image: "/images/teachers/johnson.jpg",
            user_id: "user_teacher_002",
          },
          subject: {
            id: "sub_physics",
            _id: "sub_physics",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "mon_break1",
          type: "break",
          title: "Morning Break",
          description: "Short break for refreshments",
          order: 2,
          start_offset: 80,
          duration_minutes: 20,
          color_code: "#F7F9FC",
          enabled: true,
        },
        {
          period_id: "mon_3",
          type: "subject",
          title: "Chemistry",
          description: "Organic Chemistry Basics",
          order: 3,
          start_offset: 100,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "sub_chemistry",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Brown",
            image: "/images/teachers/brown.jpg",
            user_id: "user_teacher_003",
          },
          subject: {
            id: "sub_chemistry",
            _id: "sub_chemistry",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "mon_4",
          type: "subject",
          title: "Biology",
          description: "Cell Biology and Genetics",
          order: 4,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#96CEB4",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "sub_biology",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            image: "/images/teachers/davis.jpg",
            user_id: "user_teacher_004",
          },
          subject: {
            id: "sub_biology",
            _id: "sub_biology",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "mon_5",
          type: "subject",
          title: "English Literature",
          description: "Shakespeare and Modern Poetry",
          order: 5,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#FFEAA7",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "sub_english",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mrs. Wilson",
            image: "/images/teachers/wilson.jpg",
            user_id: "user_teacher_005",
          },
          subject: {
            id: "sub_english",
            _id: "sub_english",
            name: "English",
            code: "ENG101",
          },
        },
        {
          period_id: "mon_free1",
          type: "subject",
          title: "Free Period",
          description: "Self-study or optional activities",
          order: 6,
          start_offset: 220,
          duration_minutes: 20,
          color_code: "#DFE6E9",
          enabled: true,
        },
        {
          period_id: "mon_lunch",
          type: "lunch",
          title: "Lunch Break",
          description: "Lunch and rest period",
          order: 7,
          start_offset: 240,
          duration_minutes: 60,
          color_code: "#FDCB6E",
          enabled: true,
        },
        {
          period_id: "mon_6",
          type: "subject",
          title: "History",
          description: "World History - 20th Century",
          order: 8,
          start_offset: 300,
          duration_minutes: 40,
          color_code: "#A29BFE",
          enabled: true,
          teacher_id: "teacher_006",
          subject_id: "sub_history",
          teacher: {
            id: "teacher_006",
            _id: "teacher_006",
            name: "Mr. Taylor",
            image: "/images/teachers/taylor.jpg",
            user_id: "user_teacher_006",
          },
          subject: {
            id: "sub_history",
            _id: "sub_history",
            name: "History",
            code: "HIS101",
          },
        },
        {
          period_id: "mon_7",
          type: "subject",
          title: "Geography",
          description: "Physical Geography and Climate",
          order: 9,
          start_offset: 340,
          duration_minutes: 40,
          color_code: "#74B9FF",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "sub_geography",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Ms. Anderson",
            image: "/images/teachers/anderson.jpg",
            user_id: "user_teacher_007",
          },
          subject: {
            id: "sub_geography",
            _id: "sub_geography",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "mon_break2",
          type: "break",
          title: "Afternoon Break",
          description: "Short break before late afternoon sessions",
          order: 10,
          start_offset: 380,
          duration_minutes: 20,
          color_code: "#F7F9FC",
          enabled: true,
        },
        {
          period_id: "mon_8",
          type: "subject",
          title: "Computer Science",
          description: "Programming Fundamentals with Python",
          order: 11,
          start_offset: 400,
          duration_minutes: 40,
          color_code: "#55EFC4",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "sub_computer",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Clark",
            image: "/images/teachers/clark.jpg",
            user_id: "user_teacher_008",
          },
          subject: {
            id: "sub_computer",
            _id: "sub_computer",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "mon_9",
          type: "subject",
          title: "Physical Education",
          description: "Basketball and Fitness Training",
          order: 12,
          start_offset: 440,
          duration_minutes: 40,
          color_code: "#81ECEC",
          enabled: true,
          teacher_id: "teacher_009",
          subject_id: "sub_pe",
          teacher: {
            id: "teacher_009",
            _id: "teacher_009",
            name: "Coach Miller",
            image: "/images/teachers/miller.jpg",
            user_id: "user_teacher_009",
          },
          subject: {
            id: "sub_pe",
            _id: "sub_pe",
            name: "Physical Education",
            code: "PE101",
          },
        },
      ],
    },

    // ==================== TUESDAY ====================
    {
      day: "Tuesday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "tue_1",
          type: "subject",
          title: "English Language",
          description: "Grammar and Composition",
          order: 0,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#FFEAA7",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "sub_english",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mrs. Wilson",
            image: "/images/teachers/wilson.jpg",
            user_id: "user_teacher_005",
          },
          subject: {
            id: "sub_english",
            _id: "sub_english",
            name: "English",
            code: "ENG101",
          },
        },
        {
          period_id: "tue_2",
          type: "subject",
          title: "Mathematics",
          description: "Geometry and Trigonometry",
          order: 1,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "sub_math",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            image: "/images/teachers/smith.jpg",
            user_id: "user_teacher_001",
          },
          subject: {
            id: "sub_math",
            _id: "sub_math",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "tue_break1",
          type: "break",
          title: "Morning Break",
          description: "Short break for refreshments",
          order: 2,
          start_offset: 80,
          duration_minutes: 20,
          color_code: "#F7F9FC",
          enabled: true,
        },
        {
          period_id: "tue_3",
          type: "subject",
          title: "Chemistry Lab",
          description: "Practical Chemistry Experiments",
          order: 3,
          start_offset: 100,
          duration_minutes: 40,
          color_code: "#45B7D1",
          enabled: true,
          teacher_id: "teacher_003",
          subject_id: "sub_chemistry",
          teacher: {
            id: "teacher_003",
            _id: "teacher_003",
            name: "Dr. Brown",
            image: "/images/teachers/brown.jpg",
            user_id: "user_teacher_003",
          },
          subject: {
            id: "sub_chemistry",
            _id: "sub_chemistry",
            name: "Chemistry",
            code: "CHEM101",
          },
        },
        {
          period_id: "tue_free1",
          type: "subject",
          title: "Free Period",
          description: "Self-study or library time",
          order: 4,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#DFE6E9",
          enabled: true,
        },
        {
          period_id: "tue_4",
          type: "subject",
          title: "Physics",
          description: "Electricity and Magnetism",
          order: 5,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "sub_physics",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            image: "/images/teachers/johnson.jpg",
            user_id: "user_teacher_002",
          },
          subject: {
            id: "sub_physics",
            _id: "sub_physics",
            name: "Physics",
            code: "PHY101",
          },
        },
        {
          period_id: "tue_5",
          type: "subject",
          title: "Biology",
          description: "Human Anatomy",
          order: 6,
          start_offset: 220,
          duration_minutes: 20,
          color_code: "#96CEB4",
          enabled: true,
          teacher_id: "teacher_004",
          subject_id: "sub_biology",
          teacher: {
            id: "teacher_004",
            _id: "teacher_004",
            name: "Ms. Davis",
            image: "/images/teachers/davis.jpg",
            user_id: "user_teacher_004",
          },
          subject: {
            id: "sub_biology",
            _id: "sub_biology",
            name: "Biology",
            code: "BIO101",
          },
        },
        {
          period_id: "tue_lunch",
          type: "lunch",
          title: "Lunch Break",
          description: "Lunch and rest period",
          order: 7,
          start_offset: 240,
          duration_minutes: 60,
          color_code: "#FDCB6E",
          enabled: true,
        },
        {
          period_id: "tue_6",
          type: "subject",
          title: "Art",
          description: "Drawing and Painting Techniques",
          order: 8,
          start_offset: 300,
          duration_minutes: 40,
          color_code: "#FD79A8",
          enabled: true,
          teacher_id: "teacher_010",
          subject_id: "sub_art",
          teacher: {
            id: "teacher_010",
            _id: "teacher_010",
            name: "Ms. Garcia",
            image: "/images/teachers/garcia.jpg",
            user_id: "user_teacher_010",
          },
          subject: {
            id: "sub_art",
            _id: "sub_art",
            name: "Art",
            code: "ART101",
          },
        },
        {
          period_id: "tue_7",
          type: "subject",
          title: "Music",
          description: "Vocal Training and Music Theory",
          order: 9,
          start_offset: 340,
          duration_minutes: 40,
          color_code: "#E84393",
          enabled: true,
          teacher_id: "teacher_011",
          subject_id: "sub_music",
          teacher: {
            id: "teacher_011",
            _id: "teacher_011",
            name: "Mr. Martinez",
            image: "/images/teachers/martinez.jpg",
            user_id: "user_teacher_011",
          },
          subject: {
            id: "sub_music",
            _id: "sub_music",
            name: "Music",
            code: "MUS101",
          },
        },
        {
          period_id: "tue_break2",
          type: "break",
          title: "Afternoon Break",
          description: "Short break before late afternoon sessions",
          order: 10,
          start_offset: 380,
          duration_minutes: 20,
          color_code: "#F7F9FC",
          enabled: true,
        },
        {
          period_id: "tue_8",
          type: "subject",
          title: "Geography",
          description: "Human Geography and Population",
          order: 11,
          start_offset: 400,
          duration_minutes: 40,
          color_code: "#74B9FF",
          enabled: true,
          teacher_id: "teacher_007",
          subject_id: "sub_geography",
          teacher: {
            id: "teacher_007",
            _id: "teacher_007",
            name: "Ms. Anderson",
            image: "/images/teachers/anderson.jpg",
            user_id: "user_teacher_007",
          },
          subject: {
            id: "sub_geography",
            _id: "sub_geography",
            name: "Geography",
            code: "GEO101",
          },
        },
        {
          period_id: "tue_free2",
          type: "subject",
          title: "Free Period",
          description: "Group projects or individual study",
          order: 12,
          start_offset: 440,
          duration_minutes: 40,
          color_code: "#DFE6E9",
          enabled: true,
        },
      ],
    },

    // ==================== WEDNESDAY ====================
    {
      day: "Wednesday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        // ... similar structure for Wednesday with order, descriptions, etc.
        {
          period_id: "wed_1",
          type: "subject",
          title: "Physics",
          description: "Waves and Optics",
          order: 0,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#4ECDC4",
          enabled: true,
          teacher_id: "teacher_002",
          subject_id: "sub_physics",
          teacher: {
            id: "teacher_002",
            _id: "teacher_002",
            name: "Prof. Johnson",
            image: "/images/teachers/johnson.jpg",
            user_id: "user_teacher_002",
          },
          subject: {
            id: "sub_physics",
            _id: "sub_physics",
            name: "Physics",
            code: "PHY101",
          },
        },
        // ... continue with other periods for Wednesday
      ],
    },

    // ==================== THURSDAY ====================
    {
      day: "Thursday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        // ... similar structure for Thursday
      ],
    },

    // ==================== FRIDAY ====================
    {
      day: "Friday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        // ... similar structure for Friday
      ],
    },

    // ==================== SATURDAY (Morning Only) ====================
    {
      day: "Saturday",
      is_holiday: false,
      start_on: "09:00",
      periods: [
        {
          period_id: "sat_1",
          type: "subject",
          title: "Mathematics",
          description: "Problem Solving Session",
          order: 0,
          start_offset: 0,
          duration_minutes: 40,
          color_code: "#FF6B6B",
          enabled: true,
          teacher_id: "teacher_001",
          subject_id: "sub_math",
          teacher: {
            id: "teacher_001",
            _id: "teacher_001",
            name: "Dr. Smith",
            image: "/images/teachers/smith.jpg",
            user_id: "user_teacher_001",
          },
          subject: {
            id: "sub_math",
            _id: "sub_math",
            name: "Mathematics",
            code: "MATH101",
          },
        },
        {
          period_id: "sat_2",
          type: "subject",
          title: "English",
          description: "Creative Writing Workshop",
          order: 1,
          start_offset: 40,
          duration_minutes: 40,
          color_code: "#FFEAA7",
          enabled: true,
          teacher_id: "teacher_005",
          subject_id: "sub_english",
          teacher: {
            id: "teacher_005",
            _id: "teacher_005",
            name: "Mrs. Wilson",
            image: "/images/teachers/wilson.jpg",
            user_id: "user_teacher_005",
          },
          subject: {
            id: "sub_english",
            _id: "sub_english",
            name: "English",
            code: "ENG101",
          },
        },
        {
          period_id: "sat_break1",
          type: "break",
          title: "Morning Break",
          description: "Short break for refreshments",
          order: 2,
          start_offset: 80,
          duration_minutes: 20,
          color_code: "#F7F9FC",
          enabled: true,
        },
        {
          period_id: "sat_3",
          type: "subject",
          title: "Computer Science",
          description: "Web Development Basics",
          order: 3,
          start_offset: 100,
          duration_minutes: 40,
          color_code: "#55EFC4",
          enabled: true,
          teacher_id: "teacher_008",
          subject_id: "sub_computer",
          teacher: {
            id: "teacher_008",
            _id: "teacher_008",
            name: "Mr. Clark",
            image: "/images/teachers/clark.jpg",
            user_id: "user_teacher_008",
          },
          subject: {
            id: "sub_computer",
            _id: "sub_computer",
            name: "Computer Science",
            code: "CS101",
          },
        },
        {
          period_id: "sat_free1",
          type: "subject",
          title: "Free Period",
          description: "Optional activities or self-study",
          order: 4,
          start_offset: 140,
          duration_minutes: 40,
          color_code: "#DFE6E9",
          enabled: true,
        },
        {
          period_id: "sat_4",
          type: "subject",
          title: "Art",
          description: "Sculpture and 3D Art",
          order: 5,
          start_offset: 180,
          duration_minutes: 40,
          color_code: "#FD79A8",
          enabled: true,
          teacher_id: "teacher_010",
          subject_id: "sub_art",
          teacher: {
            id: "teacher_010",
            _id: "teacher_010",
            name: "Ms. Garcia",
            image: "/images/teachers/garcia.jpg",
            user_id: "user_teacher_010",
          },
          subject: {
            id: "sub_art",
            _id: "sub_art",
            name: "Art",
            code: "ART101",
          },
        },
      ],
    },

    // ==================== SUNDAY (Free Day) ====================
    {
      day: "Sunday",
      is_holiday: true,
      start_on: "09:00",
      periods: [], // No periods on Sunday - complete free day
    },
  ],

  class: {
    id: "class_10A",
    _id: "class_10A",
    name: "Class 10A",
    username: "class_10a_2024",
    image: "/images/classes/10a.jpg",
  },

  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2024-01-15T10:00:00Z",
};
